### ISSUE TITLE
[1.12.2] Crash with current latest version of Atum

### ISSUE THREAD

**Issue by aking4125** [yungnickyoung/YUNGs-Better-Mineshafts#19]
Hello!

After updating Atum to 2.0.18 and using Better Mineshafts 2.1.0 (Both on 1.12.2). Upon loading a world, the game crashes with the following crash report. 

Downgrading Atum to 2.0.17 works. I see in the changelog for Atum that they added events to Caves & Mineshafts so unknown if Bettercaves is also affected by this.

[crash-2020-09-18_22.17.44-server.txt](https://github.com/yungnickyoung/YUNGs-Better-Mineshafts/files/5248977/crash-2020-09-18_22.17.44-server.txt)

**Comment by ghost** [comment]
I have something like you :D

[crash-2020-09-19_11.40.38-server.txt](https://github.com/yungnickyoung/YUNGs-Better-Mineshafts/files/5249490/crash-2020-09-19_11.40.38-server.txt)

**Comment by yungnickyoung** [comment]
Hey, please report this to the Atum devs. It's on their end, I believe.

**Comment by aking4125** [comment]
The report was mentioned to the Atum2 Dev as mentioned above.

**Comment by yungnickyoung** [comment]
Unfortunately it seems they instantly closed the issue. They require the mineshafts used to inherit their own `MapGenAtumMineshaft` class, which really is not proper usage of the event bus. It guarantees that any mod that changes mineshaft generation without directly plugging into Atum will cause a crash. I suggested what I believe to be the appropriate change in the issue above, but I'm not sure they'll see it since they already closed it.

**Comment by aking4125** [comment]
Yeah I've read. I guess for the time being it'd probably should be listed as incompatible to avoid any further issues? Probably should just wait a bit.

**Comment by MrUnknownly** [comment]
ooo

**Comment by yungnickyoung** [comment]
They've posted a test build in the linked issue. Give it a try and let me know if it works

**Comment by aking4125** [comment]
Already tested. Works fine so far!

**Comment by aking4125** [comment]
Atum was updated to 2.0.19 on Curseforge. I'm still not getting any issues related to this so. I'm gonna assume the issue is fixed.
