### ISSUE TITLE
Aboveground and Underwater Generation

### ISSUE THREAD

**Issue by decon-structed** [yungnickyoung/YUNGs-Better-Mineshafts#2]
Can you stop mineshafts from generating aboveground and underwater? I've seen this happen in two seeds, though this one at spawn was the only one I was able to find again:

8347598419420470852

**Comment by decon-structed** [comment]
Thanks! Do you have any idea when this might be implemented? I need to decide if I should delay my server release for it.

**Comment by yungnickyoung** [comment]
Hard to say. It won't be at least for a month, probably.

**Comment by decon-structed** [comment]
Good to know, thanks. 
I've noticed the above-ground mineshafts only seem to occur in Badlands biomes. For my own purposes, I might just fork this and disable Better Mineshafts in Badlands and ocean biomes if I can.

**Comment by yungnickyoung** [comment]
This is actually intentional, because this is what vanilla mineshafts do. They raise the y-coordinate for badlands so that they break the surface. Of course, this doesn't really work for my mineshafts since the structure is much larger. The code is just still there since I was in a rush to make it for the ModFest and didn't have time to tweak any positioning logic.
In the future I imagine I'll be making the range of possible y-coordinates the same for all biomes (except maybe oceans). If you want to undo the y-coordinate fix for yourself or disable them altogether in some biomes, go for it. It should be pretty easy. Just look at https://github.com/yungnickyoung/YUNGs-Better-Mineshafts/blob/5bd8e260a7586c6799dc905a046c5094de748d6a/src/main/java/com/yungnickyoung/minecraft/bettermineshafts/FeatureAdder.java#L20 and disable the biome categories you don't want.

**Comment by decon-structed** [comment]
Can you tell me how you compile the jar? I use `./gradlew jar` but that gives minecraft a startup error: `java.lang.ClassNotFoundException: net.minecraft.util.registry.Registry`

**Comment by yungnickyoung** [comment]
Try `./gradlew build`
