### ISSUE TITLE
Updated to 1.16.5 and getting "Yung's better mineshafts had failed to load corrrectly

### ISSUE THREAD

**Issue by Talyda** [yungnickyoung/YUNGs-Better-Mineshafts#39]
Was playing fine on 1.16.4 yesterday (with the same version of the mod I am pretty sure!) Remembered the message about deleting the config when I updated originally, so the first time it crashed with same error I did that again, just in case it needed it again

crash log:  https://pastebin.com/SxvdXaGm
latest.log: https://pastebin.com/NsPn0LXY

If you need any other info, just holler! =)

*edits* just realised total brain fart and didn't include versions, though I think one of those logs has them in
YungsApi forge-3
BetterMineshafts 2.0

**Comment by Talyda** [comment]
Downgrading YungsApi to version 2.0 let me start up =)

**Comment by yungnickyoung** [comment]
Hey, thanks for reporting this.

Can you pastebin all of the files generated in the `bettermineshafts` directory? E.g. `biomeTags.txt,` `README.txt`, `variants.json`. I know it's a bit of work to do that, but it would help me out a lot.

Also, be careful using API Forge-2. It's not supported and may cause issues.

**Comment by Talyda** [comment]
Sure! I updated back to YungsApi-1.16.4-Forge-3 cos I assumed that you needed the files after that - but they don't appear to have changed at all in the past couple days anyway

There's two readme files, cos of the file structure.

The one in "config\bettermineshafts" is here:  https://pastebin.com/w7b4X8ag


The one in "config\bettermineshafts\1_16" is here: https://pastebin.com/ScEAjPey

biomeTags.txt just has one line:  "Helper file showing all available BiomeDictionary biome tags."

variants.json is here: https://pastebin.com/kAT4tjVA

(those are in the "config\bettermineshafts\1_16 folder too)

**Comment by yungnickyoung** [comment]
Thanks! And yeah be careful playing with that because your variants.json is super messed up.

**Comment by Talyda** [comment]
I haven't changed it I don't think?

I messed with better caves a bit, but pretty sure I didn't touch that one!

**Comment by yungnickyoung** [comment]
I know, something is causing it to generate improperly. Not sure what.

**Comment by Talyda** [comment]
Ah! ok, I will not do too much in the world yet then =)
I did actually make a copy of my instance and put everything back to 1.16.4 to play with for now =)

**Comment by yungnickyoung** [comment]
Ok, so I think I understand what's going on here.

Let's say you're starting from scratch - no `bettermineshafts` directory exists at all.

If you run v2.0 with YUNG's API Forge-2, the game will crash on startup with a `NoSuchMethodError`. This is because API Forge-2 is missing a required method I use in BM 2.0 for JSON serialization. This will result in your `biomeTags.txt` not actually listing any biome tags, as well as the `variants.json` not generating at all.

So, having experienced that crash, you then update YUNG's API to Forge-3. This actually should fix the problem entirely, with the only outstanding issue being that your biomeTags.txt is still empty. However, this file is purely to assist users, and doesn't actually have a function. So your game should work fine.

Now, what I suspect you did (as well as others who are having this issue), is that you then downgraded YUNG's API back to Forge-2. That version is unable to parse the `variants.json` generated by API Forge-3, resulting in the crash you experienced.

If you delete the `bettermineshafts` directory entirely, and start the game with both BM 2.0 and API Forge-3, everything should work fine.

Edit: Better Mineshafts v2.0.1 now properly requires YUNG's API 1.16.4-Forge-3+. This will hopefully prevent such confusing issues caused by the use of older API versions. Will leave this issue open for a little while for visibility.

**Comment by Talyda** [comment]
While I can't be sure of exactly when I updated what, I am almost certain that I didn't downgrade to Yungs API forge-2 until this morning after I had tried deleting the config and restarting a couple of times with no luck (with the error that brought me here)

However, whatever happened, yes, deleting the bettermineshafts directory out of the config directory has allowed the game to start up again! Thanks for such a quick response!

Now off to se if the mineshaft I found last night before I turned the game off is still there, or if I messed it up! =o
