### ISSUE TITLE
[Suggestion] Add config options for Mineshafts such as position, rarity, and size!

### ISSUE THREAD

**Issue by TelepathicGrunt** [yungnickyoung/YUNGs-Better-Mineshafts#4]
Just a quick suggestion that people may enjoy. Adding config options to change the spawnrates of the Mineshafts, how big they can get, and the Y value range would be super helpful! And if you do add biome variants, a way to turn on or off each variant would be nice. :)

**Comment by yungnickyoung** [comment]
Spawnrate option will definitely be in there. Biome variant toggling is a maybe - it would be nice, but isn't a priority for initial release at this point.

As for how big they can get, I'm not sure. I'm designing the structure to be of a certain variable size as part of what I think is the best design. So it's one of those things where if enough people ask for it, I'll add it, but I'd rather not, since I think the default will be satisfactory for most users. Allowing users to vary size could also result in the structure hitting the chunk range cap, resulting in pieces cut off along chunk boundaries, and I'd like to avoid having to deal with that.

Y-value range control is a good idea, e.g. if users have a high liquid altitude set with Better Caves, so I'll prob add that.

Btw is there a plugin or something for implementing user config on Fabric? I haven't looked into it.

**Comment by TelepathicGrunt** [comment]
I use Cotton as it’s pretty easy to setup, has comments, handles the data types I need like ints, strings, etc, and the config can be changed while in game.  However, it does not restrict values so range checking has to be done in code and the config part of cotton is actually a small part of cotton so you end up with a bit of bloat.

Some people use Gson instead and read from that directly which is a lot less bloat. Then there’s quite a few other config libraries floating around as Fabric is still arguing over what the best config format is to add to the Fabric API lol.

**Comment by yungnickyoung** [comment]
Added config options for all Forge versions. I decided not to bother with Fabric for now.
