### ISSUE TITLE
[1.12.2] TNT and furnace minecarts render as black

### ISSUE THREAD

**Issue by lazarusgreen** [yungnickyoung/YUNGs-Better-Mineshafts#50]
The mod causes the textures of TNT and furnace minecarts to break - they only hold black cubes.

![image](https://user-images.githubusercontent.com/61564109/109786457-75efc900-7c0d-11eb-9984-0a3f358889aa.png)

**Comment by yungnickyoung** [comment]
I think this is just 1.12 rendering jankess that I have no control over, sadly.

**Comment by xJon** [comment]
I also encountered this - my workaround was to disable them from generating in the first place through the config file.

**Comment by yungnickyoung** [comment]
Closing bc 1.12 rendering nonsense that to my knowledge can't be fixed easily

**Comment by embeddedt** [comment]
This is probably [MC-6932](https://bugs.mojang.com/browse/MC-6932) which is fixed in 1.15+. I have written [this one-liner](https://github.com/embeddedt/Sledgehammer/blob/9f3505233e33091a3068e2aef1ab9d2b76d89979/src/main/java/io/github/lxgaming/sledgehammer/mixin/core/client/renderer/entity/RenderMinecartMixin.java) for 1.12 which seems to fix the issue, however I need to do more testing to ensure it doesn't break anything else.
