### ISSUE TITLE
Serverside Crash on Startup - 1.15.2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [yungnickyoung/YUNGs-Better-Mineshafts#6]
Please note this is not a new world so this crash is providing you with info when migrating pre-existing worlds. 

https://gist.github.com/P3rf3ctXZer0/4d9bfc6dedd999b636a5ce995f17bcc7

**Comment by P3rf3ctXZer0** [comment]
I will not test on a new world if you are interested in testing you can get the latest pack from here.
https://github.com/P3rf3ctXZer0/mc-1.15.2-Pokecube-Evolved/releases/tag/5.6.0

Its a curse pack with 4Gb dedicted to minecraft and 4Gb Dedicated to your pc. I reccomend a pc with at least 8Gb.

**Comment by yungnickyoung** [comment]
Hey, thanks for the bug report. If you don't mind, please try running your server with the dev jar file from here: https://github.com/yungnickyoung/YUNGs-Better-Mineshafts/releases/tag/forge-1.15.2-1.0.1-dev

The server _should_ no longer crash. Please then post your logs here, as there should be at least 1 error message that will help me find the source of the problem. Note that if the server doesn't crash, I haven't actually fixed the root cause, but rather just made a sort of temporary band-aid fix.

**Comment by P3rf3ctXZer0** [comment]
Sure I can use my test bench.

**Comment by P3rf3ctXZer0** [comment]
Question should the client still use the release build?

**Comment by yungnickyoung** [comment]
I don't think you need to test connecting to the server, just starting it up and then sending the log should suffice. The error occurs during initial server startup and I think is independent of clients connecting

**Comment by P3rf3ctXZer0** [comment]
Okay.

**Comment by yungnickyoung** [comment]
Nvm don't worry about it, I think I've found the issue. Looking into fixing it now

**Comment by P3rf3ctXZer0** [comment]
What I just got the logs. :( https://gist.github.com/P3rf3ctXZer0/e1fc8e6263c486894bcc26e87dd9bb8e

**Comment by yungnickyoung** [comment]
Ah sorry about that. Your logs do confirm my suspicions though. Looks like the error happens when checking to see if a biome contains vanilla mineshafts. I just found a much easier way to perform the check which should avoid any errors, so if all goes well I'll upload a fixed version on CurseForge within an hour.
