### ISSUE TITLE
I got an issue

### ISSUE THREAD

**Issue by Redmoonhd1** [yungnickyoung/YUNGs-Better-Mineshafts#73]
so when i put Yungs api in my mods folder and try starting it crashes and says Exit code: 0 anyone knows how to fix it?

**Comment by yungnickyoung** [comment]
Double check you're using the correct version for all of your mods. Generally speaking, this exit code tends to happen when users use a mod for the wrong loader or MC version.

Gonna close this btw, because this is the Better Mineshafts issue tracker. Feel free to ask for help in the [Discord](discord.gg/rns3beq)
